# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: power78

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080
